// Declarative actions: what `plan`-generated flows are made of. Interpreted at run time, which is
// what makes self-healing possible (a failed action can be swapped for a repaired one and the flow
// file rewritten). Hand-written flows use step.run and full Playwright instead.
const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export function locatorFor(t, target) {
	if (!target) throw new Error("action needs a target");
	if (target.css) return t.page.locator(target.css).first();
	if (target.role) return t.page.getByRole(target.role, { name: new RegExp(escapeRegex(target.name || ""), "i") }).first();
	if (target.text) return t.page.getByText(target.text, { exact: false }).first();
	throw new Error(`bad target: ${JSON.stringify(target)}`);
}

export async function runAction(t, a) {
	switch (a.kind) {
		case "goto": return t.goto(a.path || a.url);
		case "click": return t.click(locatorFor(t, a.target));
		case "fill": return t.fill(locatorFor(t, a.target), a.value ?? "", { redact: !!a.redact });
		case "press": return t.press(a.value);
		case "hover": return t.hover(locatorFor(t, a.target));
		case "scroll": return t.scrollBy(a.px ?? 900, { label: a.label || "" });
		case "waitFor": return t.waitFor(locatorFor(t, a.target));
		case "waitLong": return t.waitLong(a.target ? locatorFor(t, a.target) : null, { label: a.label || "waiting" });
		case "pause": return t.pause(a.seconds ?? 1.2);
		default: throw new Error(`unknown action kind: ${a.kind}`);
	}
}

// healCtx: { selfHeal({t, step, action, error}) -> replacement action | null, onHealed(step, i, action) }
export function makeRun(step, healCtx) {
	return async (t) => {
		for (let i = 0; i < step.actions.length; i++) {
			try {
				await runAction(t, step.actions[i]);
			} catch (err) {
				const healed = healCtx?.selfHeal ? await healCtx.selfHeal({ t, step, action: step.actions[i], error: err }) : null;
				if (!healed) throw err;
				await runAction(t, healed);
				step.actions[i] = healed;
				healCtx.onHealed?.(step, i, healed);
			}
		}
	};
}

export function codegenFlow(spec) {
	const clean = {
		id: spec.id,
		title: spec.title,
		goal: spec.goal || "",
		auth: spec.auth ?? false,
		steps: spec.steps.map((s) => ({ id: s.id, say: s.say || "", actions: s.actions })),
	};
	return `// generated by tutorial-kit plan (declarative, self-healing). Edit freely.\nexport default ${JSON.stringify(clean, null, "\t")};\n`;
}
