// Declarative actions: what `plan`-generated flows are made of. Interpreted at run time, which is
// what makes self-healing possible (a failed action can be swapped for a repaired one and the flow
// file rewritten). Hand-written flows use step.run and full Playwright instead.
import { validateFlow, validateAction } from "./validate.mjs";
import { sameOriginUrl } from "../security/urls.mjs";

const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export function locatorFor(t, target) {
	if (!target) throw new Error("action needs a target");
	if (target.css) return t.page.locator(target.css).first();
	// exact: whole-string match. Without it /Credits/i also matches "Earn 100 credits" CTAs.
	if (target.role) {
		const name = target.exact
			? new RegExp(`^${escapeRegex(target.name || "")}$`, "i")
			: new RegExp(escapeRegex(target.name || ""), "i");
		return t.page.getByRole(target.role, { name }).first();
	}
	if (target.text) return t.page.getByText(target.text, { exact: !!target.exact }).first();
	throw new Error(`bad target: ${JSON.stringify(target)}`);
}

export async function runAction(t, a) {
	validateAction(a, t.baseUrl);
	switch (a.kind) {
		case "goto":
			return t.goto(sameOriginUrl(a.path ?? a.url, t.baseUrl));
		case "click":
			return t.click(locatorFor(t, a.target));
		case "fill":
			return t.fill(locatorFor(t, a.target), a.value ?? "", { redact: !!a.redact });
		case "press":
			return t.press(a.value);
		case "hover":
			return t.hover(locatorFor(t, a.target));
		case "scroll":
			return t.scrollBy(a.px ?? 900, { label: a.label || "" });
		case "waitFor":
			return t.waitFor(locatorFor(t, a.target));
		case "waitLong":
			return t.waitLong(a.target ? locatorFor(t, a.target) : null, {
				label: a.label || "waiting",
				timeout: (a.timeoutSec ?? 300) * 1000,
			});
		case "pause":
			return t.pause(a.seconds ?? 1.2);
		default:
			throw new Error(`unknown action kind: ${a.kind}`);
	}
}

// healCtx: { selfHeal({t, step, action, error}) -> replacement action | null, onHealed(step, i, action) }
export function makeRun(step, healCtx) {
	return async (t) => {
		for (let i = 0; i < step.actions.length; i++) {
			try {
				await runAction(t, step.actions[i]);
			} catch (err) {
				// noHeal: the target is correct and a timeout means the product is slow or stuck,
				// not that a selector drifted. Healing there just picks a plausible wrong element.
				const canHeal = healCtx?.selfHeal && !step.actions[i].noHeal;
				const healed = canHeal
					? await healCtx.selfHeal({ t, step, action: step.actions[i], error: err })
					: null;
				if (!healed) throw err;
				await runAction(t, healed);
				step.actions[i] = healed;
				healCtx.onHealed?.(step, i, healed);
			}
		}
	};
}

export function codegenFlow(spec) {
	validateFlow(spec, { declarativeOnly: true });
	const clean = {
		id: spec.id,
		title: spec.title,
		goal: spec.goal || "",
		auth: spec.auth ?? false,
		...(spec.zoom !== undefined ? { zoom: spec.zoom } : {}),
		steps: spec.steps.map((s) => ({ id: s.id, say: s.say || "", actions: s.actions })),
	};
	return `// generated by tutorial-kit plan (declarative, self-healing). Edit freely.\nexport default ${JSON.stringify(clean, null, "\t")};\n`;
}

// A tutorial step should present ONE screen: its chip label and narration span the whole step, so
// if a navigation (a "Next"/"Continue"/"Create"/goto) sits BETWEEN two dwelling pauses, the step
// shows the pre- and post-navigation screens under one label. That is the bug where "Choose voice"
// rendered over the visuals picker. The fix is one screen per step: navigate at the FRONT
// (nav -> pause), never pause -> nav -> pause. Returns human-readable warnings.
const NAV_NAME = /^(next|continue|create|launch|generate|save|start|finish|done)\b/i;
const isNav = (a) =>
	a.kind === "goto" ||
	((a.kind === "click" || a.kind === "press") && NAV_NAME.test(a.target?.name || a.value || ""));
const isDwell = (a) => a.kind === "pause" && (a.seconds ?? 1.2) >= 1;

export function lintFlow(flow) {
	const warnings = [];
	for (const step of flow.steps || []) {
		const acts = step.actions || [];
		for (let j = 0; j < acts.length; j++) {
			if (!isNav(acts[j])) continue;
			const dwellBefore = acts.slice(0, j).some(isDwell);
			const dwellAfter = acts.slice(j + 1).some(isDwell);
			if (dwellBefore && dwellAfter) {
				warnings.push(
					`${flow.id} / step "${step.id}": pauses before AND after a navigation (${acts[j].target?.name || acts[j].value || acts[j].kind}). ` +
						`The label and narration will straddle two screens. Split into one screen per step (navigate at the front).`,
				);
				break;
			}
		}
	}
	return warnings;
}
